extended TaskQueueDelegate, TaskObserver protocols
arikis/Overdrive pull request #13
Opened 2017-02-17 15:00 UTC by RaimarT

…askObserver by taskWillFinishExecution(_:), adapted FinishBlockObserver and Task, extended appropriate tests

2017-03-20 17:49 UTC, RaimarT commented on Sources/Overdrive/TaskObserver.swift
> +    public func taskWillFinishExecution<T>(_ task: Task<T>) {
I did not provide the result argument in the function signature because a task might transition to `finished` state without necessarily having a non-optional result if cancelled.

The advantage of being notified of a task that WILL finish is to be able to react on the result before the task actually finishes. This is especially useful if you have multiple tasks enqueued within a queue whose `maxConcurrentTaskCount` is limited to a certain count of tasks and those tasks do not have direct dependencies for managing task conditions. In my case there are some heavy-lifting operations enqueued (maxConcurrentTaskCount = 2) which should be aborted if any task fails. Being able to access the first task's result before it actually finishes makes it possible to cancel all other tasks. Just using `taskDidFinishExecution` causes at least one more task to execute because OperationQueue detects the first task's `finished`,  starts the next task and afterwards `taskDidFinishExecution` is being called.

2017-03-28 11:41 UTC, arikis commented on Sources/Overdrive/TaskObserver.swift
> +    public func taskWillFinishExecution<T>(_ task: Task<T>) {
What about this:

```swift
func taskWillFinishExecution(_ task: Task<T>, with result: Result<T>? = nil)
```
This would also work if task finishes with `result = nil`.

> result can be easily accessed using the task's result property.

`result` property is populated only after task changes state to `.finished`. If we're to introduce this method it should probably be good to provide the actual result.

On the side note, what prevents you from using dependencies in that case?

2017-03-28 11:44 UTC, saidsikira requested changes
Great job!

2017-03-28 11:44 UTC, arikis commented on Sources/Overdrive/State.swift
> -//  State.swift
Any particular reason for this?

2017-03-28 11:44 UTC, arikis commented on Sources/Overdrive/TaskBase.swift
> +        func canTransition(to state: State, ifCancelled cancelled: Bool) -> Bool {
I think that `isCancelled` is better than `ifCancelled` since iOS developers are more used to `is` prefix. Also, it would be good to update documentation for this method (rename `cancelled` to `isCancelled`).

2017-03-28 12:15 UTC, RaimarT commented on Sources/Overdrive/TaskObserver.swift
> +    public func taskWillFinishExecution<T>(_ task: Task<T>) {
In your current implementation `self.result = result` is set before calling `moveToFinishedState()` so it should be accessible at the time `taskWillFinishExecution()` is called.

Since I can hardly predict how much time which task will consume (a few seconds up to 2 minutes) setting dependencies would limit task queue's capabilities. Because a task can only run if all dependent task have finished, at some point of time there might be several tasks left in the queue having chained dependencies resulting in serial queue behavior. Without dependencies this would only be the case for the last task enqueued.

2017-03-28 12:43 UTC, RaimarT commented on Sources/Overdrive/State.swift
> -//  State.swift
Unlike e.g. `Result` enum which can be commonly used in several scenarios the `State` enum is solely used and useful in conjunction with a Task(Base). So it should be encapsulated within TaskBase to clarify that this is a Task.State.

2017-03-28 12:51 UTC, RaimarT commented on Sources/Overdrive/TaskBase.swift
> +        func canTransition(to state: State, ifCancelled cancelled: Bool) -> Bool {
I chose `ifCancelled` to emphasize the transition is possible **on condition that** task is cancelled but `isCancelled` would be fine for me, too.

2017-03-28 13:00 UTC, arikis commented on Sources/Overdrive/TaskObserver.swift
> +    public func taskWillFinishExecution<T>(_ task: Task<T>) {
Thanks for clarification.

2017-03-28 13:00 UTC, arikis commented on Sources/Overdrive/TaskBase.swift
> +        func canTransition(to state: State, ifCancelled cancelled: Bool) -> Bool {
Let's update it then, so I can merge the PR.

2017-03-28 13:02 UTC, arikis commented on Tests/OverdriveTests/TaskQueueDelegateTests.swift
> +
@RaimarT and please fix this violation.

2017-03-28 13:29 UTC, saidsikira approved these changes

2017-03-28 13:40 UTC, merged